"""empty message

Revision ID: 30f300275197
Revises: 
Create Date: 2024-03-13 16:29:22.854933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f300275197'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('coffee_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(length=200), nullable=False),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shops.id'], name=op.f('fk_coffee_menus_coffee_shop_id_coffee_shops')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffee_shop_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shops.id'], name=op.f('fk_coffee_shop_reviews_coffee_shop_id_coffee_shops')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffee_shop_reviews')
    op.drop_table('coffee_menus')
    op.drop_table('users')
    op.drop_table('coffee_shops')
    # ### end Alembic commands ###
